/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fibnative_FibLib */

#ifndef _Included_com_example_fibnative_FibLib
#define _Included_com_example_fibnative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fibnative_FibLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibnative_FibLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_fibnative_FibLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibnative_FibLib_fibNI
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_fibnative_FibLib
 * Method:    getFileData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_fibnative_FibLib_getFileData
  (JNIEnv *, jclass);

/*
 * Class:     com_example_fibnative_FibLib
 * Method:    setFileData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_fibnative_FibLib_setFileData
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_example_fibnative_FibLib
 * Method:    abc
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_fibnative_FibLib_abc
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
