/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fibnative_FileLib */

#ifndef _Included_com_example_fibnative_FileLib
#define _Included_com_example_fibnative_FileLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fibnative_FileLib
 * Method:    getFileData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_fibnative_FileLib_getFileData
  (JNIEnv *, jclass);

/*
 * Class:     com_example_fibnative_FileLib
 * Method:    setFileData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_fibnative_FileLib_setFileData
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
